/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KamiRouteImport } from './routes/kami'
import { Route as HubungiRouteImport } from './routes/hubungi'
import { Route as UlasanIndexRouteImport } from './routes/ulasan/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as PenulisIndexRouteImport } from './routes/penulis/index'
import { Route as KategoriIndexRouteImport } from './routes/kategori/index'
import { Route as DewanIndexRouteImport } from './routes/dewan/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as UlasanSlugRouteImport } from './routes/ulasan/$slug'
import { Route as ProdukIdRouteImport } from './routes/produk/$id'
import { Route as PenulisSlugRouteImport } from './routes/penulis/$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori/$slug'
import { Route as ArtikelSlugRouteImport } from './routes/artikel/$slug'

const KamiRoute = KamiRouteImport.update({
  id: '/kami',
  path: '/kami',
  getParentRoute: () => rootRouteImport,
} as any)
const HubungiRoute = HubungiRouteImport.update({
  id: '/hubungi',
  path: '/hubungi',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasanIndexRoute = UlasanIndexRouteImport.update({
  id: '/ulasan/',
  path: '/ulasan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenulisIndexRoute = PenulisIndexRouteImport.update({
  id: '/penulis/',
  path: '/penulis/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIndexRoute = KategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const DewanIndexRoute = DewanIndexRouteImport.update({
  id: '/dewan/',
  path: '/dewan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasanSlugRoute = UlasanSlugRouteImport.update({
  id: '/ulasan/$slug',
  path: '/ulasan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PenulisSlugRoute = PenulisSlugRouteImport.update({
  id: '/penulis/$slug',
  path: '/penulis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/hubungi': typeof HubungiRoute
  '/kami': typeof KamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/penulis/$slug': typeof PenulisSlugRoute
  '/produk/$id': typeof ProdukIdRoute
  '/ulasan/$slug': typeof UlasanSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/dewan/': typeof DewanIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/penulis/': typeof PenulisIndexRoute
  '/produk/': typeof ProdukIndexRoute
  '/ulasan/': typeof UlasanIndexRoute
}
export interface FileRoutesByTo {
  '/hubungi': typeof HubungiRoute
  '/kami': typeof KamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/penulis/$slug': typeof PenulisSlugRoute
  '/produk/$id': typeof ProdukIdRoute
  '/ulasan/$slug': typeof UlasanSlugRoute
  '/artikel': typeof ArtikelIndexRoute
  '/dewan': typeof DewanIndexRoute
  '/kategori': typeof KategoriIndexRoute
  '/penulis': typeof PenulisIndexRoute
  '/produk': typeof ProdukIndexRoute
  '/ulasan': typeof UlasanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/hubungi': typeof HubungiRoute
  '/kami': typeof KamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/penulis/$slug': typeof PenulisSlugRoute
  '/produk/$id': typeof ProdukIdRoute
  '/ulasan/$slug': typeof UlasanSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/dewan/': typeof DewanIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/penulis/': typeof PenulisIndexRoute
  '/produk/': typeof ProdukIndexRoute
  '/ulasan/': typeof UlasanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hubungi'
    | '/kami'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/penulis/$slug'
    | '/produk/$id'
    | '/ulasan/$slug'
    | '/artikel/'
    | '/dewan/'
    | '/kategori/'
    | '/penulis/'
    | '/produk/'
    | '/ulasan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hubungi'
    | '/kami'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/penulis/$slug'
    | '/produk/$id'
    | '/ulasan/$slug'
    | '/artikel'
    | '/dewan'
    | '/kategori'
    | '/penulis'
    | '/produk'
    | '/ulasan'
  id:
    | '__root__'
    | '/hubungi'
    | '/kami'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/penulis/$slug'
    | '/produk/$id'
    | '/ulasan/$slug'
    | '/artikel/'
    | '/dewan/'
    | '/kategori/'
    | '/penulis/'
    | '/produk/'
    | '/ulasan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HubungiRoute: typeof HubungiRoute
  KamiRoute: typeof KamiRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  PenulisSlugRoute: typeof PenulisSlugRoute
  ProdukIdRoute: typeof ProdukIdRoute
  UlasanSlugRoute: typeof UlasanSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  DewanIndexRoute: typeof DewanIndexRoute
  KategoriIndexRoute: typeof KategoriIndexRoute
  PenulisIndexRoute: typeof PenulisIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
  UlasanIndexRoute: typeof UlasanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kami': {
      id: '/kami'
      path: '/kami'
      fullPath: '/kami'
      preLoaderRoute: typeof KamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubungi': {
      id: '/hubungi'
      path: '/hubungi'
      fullPath: '/hubungi'
      preLoaderRoute: typeof HubungiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasan/': {
      id: '/ulasan/'
      path: '/ulasan'
      fullPath: '/ulasan/'
      preLoaderRoute: typeof UlasanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penulis/': {
      id: '/penulis/'
      path: '/penulis'
      fullPath: '/penulis/'
      preLoaderRoute: typeof PenulisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/': {
      id: '/kategori/'
      path: '/kategori'
      fullPath: '/kategori/'
      preLoaderRoute: typeof KategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dewan/': {
      id: '/dewan/'
      path: '/dewan'
      fullPath: '/dewan/'
      preLoaderRoute: typeof DewanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasan/$slug': {
      id: '/ulasan/$slug'
      path: '/ulasan/$slug'
      fullPath: '/ulasan/$slug'
      preLoaderRoute: typeof UlasanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penulis/$slug': {
      id: '/penulis/$slug'
      path: '/penulis/$slug'
      fullPath: '/penulis/$slug'
      preLoaderRoute: typeof PenulisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HubungiRoute: HubungiRoute,
  KamiRoute: KamiRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  PenulisSlugRoute: PenulisSlugRoute,
  ProdukIdRoute: ProdukIdRoute,
  UlasanSlugRoute: UlasanSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  DewanIndexRoute: DewanIndexRoute,
  KategoriIndexRoute: KategoriIndexRoute,
  PenulisIndexRoute: PenulisIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
  UlasanIndexRoute: UlasanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
